name: Core Docker Builder
on:
  workflow_call:
    inputs:
      distro_data:
        required: true
        type: string # JSON string containing the matrix row
    secrets:
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Date and Build ID
        id: vars
        run: |
          DATE=$(date +'%Y%m%d')
          echo "date=$DATE" >> $GITHUB_OUTPUT
          echo "build_id=$DATE.${{ github.run_number }}" >> $GITHUB_OUTPUT

      # Part 1: systemd-distro
      - name: Build Systemd Base
        uses: docker/build-push-action@v5
        with:
          context: ${{ fromJSON(inputs.distro_data).systemd-distro.context }}
          file: ${{ fromJSON(inputs.distro_data).systemd-distro.dockerfile }}
          platforms: ${{ fromJSON(inputs.distro_data).systemd-distro.platforms }}
          push: true
          # Forces a pull of the base image to ensure it exists locally
          pull: true
          tags: ${{ fromJSON(inputs.distro_data).systemd-distro.tags }}
          build-args: |
            BUILD_ID=${{ steps.vars.outputs.build_id }}
            BUILD_DATE=${{ steps.vars.outputs.date }}

      # Part 2: systemd-python-distro
      - name: Build Systemd Python
        uses: docker/build-push-action@v5
        with:
          context: ${{ fromJSON(inputs.distro_data).systemd-python-distro.context }}
          file: ${{ fromJSON(inputs.distro_data).systemd-python-distro.dockerfile }}
          platforms: ${{ fromJSON(inputs.distro_data).systemd-python-distro.platforms }}
          push: true
          # Forces a pull of the base image to ensure it exists locally
          pull: true
          tags: ${{ fromJSON(inputs.distro_data).systemd-python-distro.tags }}
          build-args: |
            IMAGE_REGISTRY=${{ github.repository_owner }}
            PYTHON_VERSION=3.13.6
            BUILD_ID=${{ steps.vars.outputs.build_id }}
            BUILD_DATE=${{ steps.vars.outputs.date }}
